name: dartemis
version: 0.7.0-dev
author: Dennis Kaselow <Dennis.Kaselow+dartemis@gmail.com>
description: An Entity System Framework for game development. Based on Artemis.
homepage: https://github.com/denniskaselow/dartemis
environment:
  sdk: '>=1.8.0 <2.0.0'
dependencies:
  bit_set: ^0.1.0
  analyzer: ^0.24.0
  barback: ^0.15.2
  dart_style: ^0.1.7
dev_dependencies:
  browser: ^0.10.0
  unittest: ^0.11.5
  mockito: ^0.8.2
# only needed for running the example
#transformers:
#- dartemis
