name: dartemis
version: 0.5.0-dev
author: Dennis Kaselow <Dennis.Kaselow+dartemis@gmail.com>
description: An Entity System Framework for game development. Based on Artemis.
homepage: https://github.com/denniskaselow/dartemis
dev_dependencies:
  browser: any
  unittest: any
