name: dartemis
version: 0.7.0-dev
author: Dennis Kaselow <Dennis.Kaselow+dartemis@gmail.com>
description: An Entity System Framework for game development. Based on Artemis.
homepage: https://github.com/denniskaselow/dartemis
environment:
  sdk: '>=0.8.10 <2.0.0'
dependencies:
  analyzer: '>=0.22.0 <0.23.0'
  barback: '>=0.15.0 <0.16.0'
dev_dependencies:
  browser: '>=0.9.0 <0.11.0'
  mock: <0.12.0
  unittest: '>=0.11.0 <0.12.0'
transformers:
#- dartemis
